alert('Assalomu alaykum')
var str  = prompt("what's your full name?")
var age = prompt("How old are you?")
var tel = prompt("Enter your phone number...")
var loct = prompt("Where are you from?  Enter your location..")
console.log(str)
console.log(age)
console.log(tel)
console.log(loct)